# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 571eb40985535b9c89077dcd5d953890af2694d876166520ff07eb38c8e7d1f2e6ab3d7995c53dfb4d16f2547d5a1c0032cbdc4856dc5a27d127b217d4eeeb9f

test:
  secret_key_base: 1573f4eda61d546e182916d35033c371998833e494a7c2525e6bcd39ee55d57875d68b68331b2613c65efb5c8452ad749b44dc75e890e88169ba605e535642b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
